### ISSUE TITLE
As a User, I want to host or join a lobby, to play the game.

### ISSUE THREAD

**Issue by lorezh** [sopra-fs23-group-06/sopra-fs23-group-06-server#1]
# Acceptance Criteria

- [x]  A user can select either Host or Join as options. 
- [x]  Hosting a game opens a new lobby that can be joined by entering a game code. 
- [x]  To join a lobby a user has to enter the game code.
- [x]  Before joining the lobby, be that as the host or a guest, a user needs to enter a username unique to the lobby to be identifiable.
- [x] No more than 6 players are allowed to join a lobby.

# Development tasks

- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#18
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#67
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#68
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#69
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#17
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#16
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#72
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#73
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#15
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#49
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#76
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#14
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#78
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#170
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#171
