### ISSUE TITLE
As a User, I want to be able to end the game and have the option to start a new game

### ISSUE THREAD

**Issue by lorezh** [sopra-fs23-group-06/sopra-fs23-group-06-server#112]
# Acceptance Criteria

- [x] At the end of the Game there should be a button at the bottom of the scoreboard with the possibility to leave the Game 
- [x] By Leaving the Game the User is redirected to the start screen and thus has the option to play another Game 

# Development tasks

- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#113
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#24
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#23
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#25
