### ISSUE TITLE
As a User, I want to have the possibility to open the rulebook to look at the rules of the game 

### ISSUE THREAD

**Issue by lorezh** [sopra-fs23-group-06/sopra-fs23-group-06-server#118]
# Acceptance Criteria

- [x] On every Page there should be a button to click on to open the Rulebook 

# Development tasks

- [ ] sopra-fs23-group-06/sopra-fs23-group-06-client#29
- [ ] sopra-fs23-group-06/sopra-fs23-group-06-client#28
- [ ] sopra-fs23-group-06/sopra-fs23-group-06-client#26

**Comment by Terebos** [comment]
all tasks solved by [36ae3dc](https://github.com/sopra-fs23-group-06/sopra-fs23-group-06-client/commit/36ae3dcf1140b56127a3f56e8be42f1c74dbf54c)
