### ISSUE TITLE
As a User, I want to be able to connect to my opponents via voice chat

### ISSUE THREAD

**Issue by lorezh** [sopra-fs23-group-06/sopra-fs23-group-06-server#124]
# Acceptance Criteria

- [ ] Once the Game starts a button is displayed which lets the User join a call for the Lobby 
- [x] The User can mute and unmute himself 
- [ ] There should be a possibility to leave and join the call whenever, as long as the game is not finished 
- [x] Every participant of the call should be able to hear each other and talk to each other 
- [ ] Once the game is finished the call should be terminated 

# Development tasks

- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#53
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#32
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#54
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#55
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#31
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#30

**Comment by bzns** [comment]
51c0d2a
