### ISSUE TITLE
As a User, I want to see a summary of points added or taken after every round.

### ISSUE THREAD

**Issue by lorezh** [sopra-fs23-group-06/sopra-fs23-group-06-server#14]
# Acceptance Criteria

- [x]  After all tricks in a round was played and the system evaluated the scores, the user should be shown a summary of the points he received this round. 
- [x]  The user should be able to see a temporary scoreboard of the previous rounds of all users. 
- [x]  The scoreboard should display the sum of all points over all rounds for every user, so see who has the lead. 

# Development tasks

- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#85
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#20
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#87
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#19
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#89
- [ ] sopra-fs23-group-06/sopra-fs23-group-06-server#90
