### ISSUE TITLE
As a User, I want to see a summary of the game scoreboard after all rounds have been played, to see who placed in what rank.

### ISSUE THREAD

**Issue by lorezh** [sopra-fs23-group-06/sopra-fs23-group-06-server#15]
# Acceptance Criteria

- [x]  After all Rounds have been played and the last rounds score summary is over, the user should see a ranking of which user got how many points. 
- [x]  The users should get ranked by points from highest to lowest and given the rank they finished in.

# Development tasks

- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#43
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#42
- [ ] sopra-fs23-group-06/sopra-fs23-group-06-server#158
