### ISSUE TITLE
As a User I want to view the scoreboard to see if I’m winning.

### ISSUE THREAD

**Issue by lorezh** [sopra-fs23-group-06/sopra-fs23-group-06-server#16]
# Acceptance Criteria

- [x] During any point of the game, the user should be able to press a button “scoreboard” to see the current scoreboard. 
- [x] The score of the last rounds and the bids of the last and current rounds should be viewable. 

# Development tasks

- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#45
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#44
- [ ] sopra-fs23-group-06/sopra-fs23-group-06-server#157
