### ISSUE TITLE
As a System, I want to be able to manage the sequence of the game in the correct order to ensure an orderly game.

### ISSUE THREAD

**Issue by lorezh** [sopra-fs23-group-06/sopra-fs23-group-06-server#5]
# Acceptance Criteria

- [x]  After a round is completed, the System starts the next round and increases the cards given out by one. 
- [x]  After every round the starting Player shifts to the left by one.
- [x]  At the end of the 10th round, the system ends the Game and proceeds to the End Game screen.

# Development tasks

- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#34
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#35
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#36
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#37
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#38
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#3
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#40
