### ISSUE TITLE
As a System, I want to be able to manage the correct order of things to do in every round. 

### ISSUE THREAD

**Issue by lorezh** [sopra-fs23-group-06/sopra-fs23-group-06-server#7]
# Acceptance Criteria

- [x]  After revealing all the bids, the system initiates the first trick. 
- [x]  After every trick, the winner of the previous one plays the first card. 
- [x]  At the end of the last trick the next round will start. 

# Development tasks

- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#50
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#51
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#52
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#53
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#54
- [x] #173 
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#10
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#9
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#7
