### ISSUE TITLE
As a System, I want the cards to be distributed correctly every round.

### ISSUE THREAD

**Issue by lorezh** [sopra-fs23-group-06/sopra-fs23-group-06-server#8]
# Acceptance Criteria

- [x] The number of cards distributed must be the same as the number of rounds the game is in (1st round = one card, 2nd round = two cards, 10th round = 10 cards, etc.). 
- [x]  Before distributing the cards every round, they must be shuffled. 
- [x]  A Deck consists of 52 Suit cards (1-13 of each color), 5 Escape cards, 5 Pirate cards, 2 Mermaid cards, 1 Scary Mary card and 1 Skull King card. 

# Development tasks

- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#19
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#20
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#21
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#2
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#1
- [x] #49

**Comment by lorezh** [comment]
# Development tasks

- [ ] Create a Deck
- [ ] Shuffle a Deck
- [ ] Distribute the same amount of cards as rounds the game is in
