### ISSUE TITLE
As a System, I want to be able to manage the order of playing the cards for every trick.

### ISSUE THREAD

**Issue by lorezh** [sopra-fs23-group-06/sopra-fs23-group-06-server#9]
# Acceptance Criteria

- [x]  The players should only be able to play cards in the correct order, the starting player is dependent on who gave out the cards in the first trick, and who won the last trick in all consecutive tricks. 
- [x]  The order of play is clockwise from the starting player, every player plays one card. 
- [x]  Every card played should be displayed in the middle to all users. 
- [x]  After all players have played a card, the winner of the trick is decided, that player receives the trick. 

# Development tasks

- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#13
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#12
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#62
- [x] sopra-fs23-group-06/sopra-fs23-group-06-client#11
- [x] sopra-fs23-group-06/sopra-fs23-group-06-server#64
